version: "3.9"
# econoeasy 이미지만을 가지고 해당 compose를 띄운다
services:
  econoeasy:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: "${DOCKERHUB_USERNAME}/econoeasy-be:${IMAGE_TAG}"
    container_name: econoeasy-be
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    # .env 파일로부터 RDB 계정 정보를 주입
    env_file:
      - ./.env
    # mysql을 컨테이너로 실행하는거기에, 초기 비번, database를 여기서 설정해야함
    environment:
      MYSQL_ROOT_PASSWORD: ${RDB_PASSWORD}
      MYSQL_DATABASE: ${RDB_DATABASE}
#      MYSQL_USER: ${RDB_USERNAME}
#      MYSQL_PASSWORD: ${RDB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # 아래 명령어를 모두 날림
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOSQL_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOSQL_PASSWORD}
      MONGO_INITDB_DATABASE: ${NOSQL_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--username", "${NOSQL_USERNAME}", "--password", "${NOSQL_PASSWORD}", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5

volumes:
  mysql_data:
  mongo_data:
