spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whiplash
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #        default_batch_fetch_size: 100
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whiplash-mongo
#      username: root
#      password:
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
