spring:
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
    driver-class-name: ${RDB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #        default_batch_fetch_size: 100
    show-sql: true
  data:
    mongodb:
      host: ${NOSQL_HOST}
      port: ${NOSQL_PORT}
      database: ${NOSQL_DATABASE}
#      username: root
#      password:
  mail:
    host: ${GMAIL_HOST}
    port: ${GMAIL_PORT}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
