spring:
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
    driver-class-name: ${RDB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  mail:
    host: ${GMAIL_HOST}
    port: ${GMAIL_PORT}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
  issuer: ${JWT_ISSUER}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

redis:
  key:
    stream-key: ${REDIS_STREAM_KEY}
    dedup-key: ${REDIS_DEDUP_KEY}
    recommend:
      keyword-recommend: ${REDIS_KEYWORD_RECOMMEND_CACHE_PREFIX}
      common-recommend: ${REDIS_COMMON_RECOMMEND_CACHE_KEY}
      stream-key: ${REDIS_RECOMMEND_STREAM_KEY}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
